### ISSUE TITLE
Images not load

### ISSUE THREAD

**Issue by YaroVolk** [devilmac/flutter_gnamgnammanga#12]
Hey devilmac,

first, I must thank for your incredible project, I very appreciate your hard effort on this project. I am currently learning to build my own applications and your project is very helpful. First, I had some issues to debug the app, so I changed android/app/build.grandle file to the from the "Flutter Demo App" and then it works, but then the images not load, so the list and the Manga title are loading, but not the entire images. I tried to copy a new website in "mangaeden.dart" file, because I thought that the problem is the server from mangaeden. Probably I made some faults. Therefore, can you help me with the images? If the problem is the server from mangaeden, what should I exactly do to change it to a new website. 

Thank you for any of your support and I appreciate your time and understanding!

Yours sincerely,
Yaro

**Comment by devilmac** [comment]
Hi Yaro,
I'm sorry for my late answer, I did not receive this notification and, honestly, I did not know that someone was using this project 😅 but I'm glad to see that someone was interested on it 😁
In the last period, I didn't have time to work on this project and I don't know if you managed to resolve the issue. Maybe these days I can go back to work on it and I can try to fix it.

**Comment by devilmac** [comment]
Hi Yaro,
I just checked the cause that prevent the manga list loading. Simply, the www.mangaeden.com seems not work, as you just said. 
See ya!

Federico
